import {
  BaseConfig,
  type ConfigArguments,
} from "jsr:@shougo/ddc-vim@10.1.0/config";

export class Config extends BaseConfig {
  // deno-lint-ignore require-await
  override async config(args: ConfigArguments) {
    args.contextBuilder.setGlobal({
      ui: "pum",
      autoCompleteEvents: [
        "CmdLineEnter",
        "CmdlineChanged",
        "InsertEnter",
        "TextChangedI",
        "TextChangedP",
        "TextChangedT",
      ],
      sources: [
        "file",
        "denippet",
        "lsp",
        "skkeleton",
        "skkeleton_okuri",
        "buffer",
        "around",
      ],
      cmdlineSources: {
        ":": ["shell_native", "cmdline", "cmdline_history", "around"],
        "@": ["input", "cmdline_history", "file"],
        ">": ["input", "cmdline_history", "file", "around"],
        "/": ["around"],
        "?": ["around"],
        "-": ["around"],
        "=": ["input"],
      },
      sourceOptions: {
        _: {
          ignoreCase: true,
          matchers: ["matcher_fuzzy"],
          sorters: ["sorter_rank", "sorter_fuzzy"],
          converters: ["converter_fuzzy"],
        },
        around: {
          matchers: ["matcher_length"],
        },
        buffer: {
          matchers: ["matcher_length"],
        },
        lsp: {
          mark: "LSP",
          forceCompletionPattern: String.raw`\.\w*|::\w*|->\w*`,
          isVolatile: true,
          sorters: ["sorter_rank", "sorter_fuzzy", "sorter_lsp_kind"],
          converters: ["converter_fuzzy", "converter_kind_labels"],
          maxItems: 20,
        },
        denippet: {
          matchers: ["matcher_fuzzy"],
          minKeywordLength: 1,
          minAutoCompleteLength: 1,
        },
        file: {
          isVolatile: true,
          minAutoCompleteLength: 1000,
          forceCompletionPattern: String.raw`\S/\S*`,
        },
        skkeleton: {
          mark: "SKK",
          matchers: [],
          sorters: [],
          converters: [],
          isVolatile: true,
          minAutoCompleteLength: 1,
        },
        skkeleton_okuri: {
          mark: "SKK*",
          matchers: [],
          sorters: [],
          converters: [],
          isVolatile: true,
        },
        cmdline: {
          mark: " ",
          isVolatile: true,
          matchers: ["matcher_fuzzy"],
          sorters: ["sorter_cmdline_history", "sorter_fuzzy"],
          converters: ["converter_fuzzy"],
          forceCompletionPattern: String.raw`\S/\S*|\.\w*`,
        },
        cmdline_history: {
          mark: " ",
        },
        shell_native: {
          mark: "ZSH",
          isVolatile: true,
          minAutoCompleteLength: 1,
          minKeywordLength: 0,
        },
      },
      sourceParams: {
        buffer: {
          requireSameFiletype: false,
        },
        lsp: {
          confirmBehavior: "replace",
          enableResolveItem: true,
          enableAdditionalTextEdit: true,
          snippetEngine: "",
        },
        file: {
          displayFile: " ",
          displayDir: " ",
          displaySym: "sym",
          displaySymFile: "sym ",
          displaySymDir: "sym ",
        },
        shell_native: {
          shell: "zsh",
        },
      },
      filterParams: {
        matcher_fuzzy: {
          splitMode: "word",
        },
        sorter_lsp_kind: {
          priority: [
            "Method",
            "Function",
            "Constructor",
            "Field",
            "Variable",
            "Class",
            "Interface",
            "Module",
            "Property",
            "Unit",
            "Value",
            "Enum",
            "Keyword",
            "Color",
            "File",
            "Reference",
            "Folder",
            "EnumMember",
            "Constant",
            "Struct",
            "Event",
            "Operator",
            "TypeParameter",
            "Text",
            "Snippet",
          ],
        },
        converter_kind_labels: {
          kindLabels: {
            Text: " ",
            Method: " ",
            Function: " ",
            Constructor: " ",
            Field: " ",
            Variable: " ",
            Class: " ",
            Interface: " ",
            Module: " ",
            Property: " ",
            Unit: " ",
            Value: " ",
            Enum: " ",
            Keyword: " ",
            Snippet: " ",
            Color: " ",
            File: " ",
            Reference: " ",
            Folder: " ",
            EnumMember: " ",
            Constant: " ",
            Struct: " ",
            Event: " ",
            Operator: " ",
            TypeParameter: " ",
          },
          kindHlGroups: {
            Method: "Function",
            Function: "Function",
            Constructor: "Function",
            Field: "Identifier",
            Variable: "Identifier",
            Class: "Structure",
            Interface: "Structure",
          },
        },
      },
    });
  }
}
